import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Layout/Header'
import Sidebar from '@/components/Layout/Sidebar'
import Avatar from '@/components/Layout/Avatar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-full h-screen bg-[#373b40]'>
        <Header />
        <Avatar />
        <div className='w-auto h-full ml-[45%] mr-[100px] z-20 '>
          {children}
        </div>
        <Sidebar />
      </body>
    </html>
  )
}
